#Hugo configuration
title = "asdf"
baseURL = "https:\/\/sadf.saf.sadf"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "saf.sadf"
